data:
  raw_dir: "data/raw/FEIS"
  preprocessed_dir: "data/preprocessed/train"
  splits_dir: "data/splits"

preprocessing:
  original_sfreq: 512 # Original sampling rate
  target_sfreq: 128 # Downsampled target rate
  channels: # Epoc X 14 channels
    [
      "AF3",
      "F7",
      "F3",
      "FC5",
      "T7",
      "P7",
      "O1",
      "O2",
      "P8",
      "T8",
      "FC6",
      "F4",
      "F8",
      "AF4",
    ]

model: eegcnn

training:
  seed: 42
  num_epochs: 200
  batch_size: 128
  learning_rate: 0.0005
  weight_decay: 0.0001
  early_stopping_patience: 10

results:
  log_dir: "results/logs"
  checkpoint_dir: "results/checkpoints"
  figures_dir: "results/figures"
